export interface InfosysProblem {
  id: number;
  problemName: string;
  topic: string;
  pattern: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  roiScore: number; // 0-100
  probabilityScore: number; // 0-100
  expectedTime: number; // in minutes
  status: 'Not Started' | 'In Progress' | 'Solved' | 'Need Revision' | 'Mastered';
  confidence: number; // 0-5 stars
  mistakes: string;
  notes: string;
  leetcode: string;
  gfg: string;
  codingNinjas: string;
  interviewBit: string;
  hackerRank: string;
  takeUForward: string;
  neetCode: string;
  day: number; // 1 to 5
  isGap: boolean;
  bookmarked?: boolean;
  favorite?: boolean;
  // Adaptive engine properties
  lastAttempted?: string; // ISO string
  nextRevisionDate?: string; // ISO string
  solveTime?: number; // actual solve time in minutes
}

export const PLATFORM_BASE_URLS = {
  leetcode: 'https://leetcode.com/problems/',
  gfg: 'https://www.geeksforgeeks.org/problems/',
  codingNinjas: 'https://www.naukri.com/code360/problems/',
  interviewBit: 'https://www.interviewbit.com/problems/',
  hackerRank: 'https://www.hackerrank.com/domains/algorithms/',
  takeUForward: 'https://takeuforward.org/',
  neetCode: 'https://neetcode.io/practice/'
};

export const initialInfosysProblems: InfosysProblem[] = [
  {
    "id": 1,
    "problemName": "Two Sum",
    "topic": "Arrays",
    "pattern": "Hash Map",
    "difficulty": "Easy",
    "roiScore": 86,
    "probabilityScore": 76,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "two-sum",
    "gfg": "1",
    "codingNinjas": "two-sum",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/",
    "neetCode": "",
    "day": 1,
    "isGap": false
  },
  {
    "id": 2,
    "problemName": "Best Time to Buy and Sell Stock",
    "topic": "Arrays",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 87,
    "probabilityScore": 77,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "best-time-to-buy-and-sell-stock",
    "gfg": "1",
    "codingNinjas": "best-time-to-buy-and-sell-stock",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/stock-buy-and-sell/",
    "neetCode": "best-time-to-buy-and-sell-stock",
    "day": 2,
    "isGap": false
  },
  {
    "id": 3,
    "problemName": "Majority Element",
    "topic": "Arrays",
    "pattern": "Hash Map",
    "difficulty": "Easy",
    "roiScore": 88,
    "probabilityScore": 78,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "majority-element",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/",
    "neetCode": "",
    "day": 3,
    "isGap": false
  },
  {
    "id": 4,
    "problemName": "Move Zeroes",
    "topic": "Arrays",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 89,
    "probabilityScore": 79,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "move-zeroes",
    "gfg": "1",
    "codingNinjas": "move-zeroes",
    "interviewBit": "move-zeroes",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-an-array/",
    "neetCode": "move-zeroes",
    "day": 4,
    "isGap": false
  },
  {
    "id": 5,
    "problemName": "Merge Sorted Array",
    "topic": "Arrays",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 90,
    "probabilityScore": 80,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "merge-sorted-array",
    "gfg": "1",
    "codingNinjas": "merge-sorted-array",
    "interviewBit": "",
    "hackerRank": "merge-sorted-array",
    "takeUForward": "https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/",
    "neetCode": "",
    "day": 5,
    "isGap": false
  },
  {
    "id": 36,
    "problemName": "Contains Duplicate",
    "topic": "Hashing",
    "pattern": "Hash Map",
    "difficulty": "Easy",
    "roiScore": 89,
    "probabilityScore": 87,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "contains-duplicate",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "contains-duplicate",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/contains-duplicate/",
    "neetCode": "contains-duplicate",
    "day": 1,
    "isGap": false
  },
  {
    "id": 37,
    "problemName": "Valid Anagram",
    "topic": "Hashing",
    "pattern": "Hash Map",
    "difficulty": "Easy",
    "roiScore": 90,
    "probabilityScore": 88,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "valid-anagram",
    "gfg": "1",
    "codingNinjas": "valid-anagram",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/check-if-two-strings-are-anagram-of-each-other/",
    "neetCode": "",
    "day": 2,
    "isGap": false
  },
  {
    "id": 38,
    "problemName": "Intersection of Two Arrays",
    "topic": "Hashing",
    "pattern": "Hash Map",
    "difficulty": "Easy",
    "roiScore": 91,
    "probabilityScore": 89,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "intersection-of-two-arrays",
    "gfg": "1",
    "codingNinjas": "intersection-of-two-arrays",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/intersection-of-two-sorted-arrays/",
    "neetCode": "intersection-of-two-arrays",
    "day": 3,
    "isGap": false
  },
  {
    "id": 39,
    "problemName": "Find All Anagrams in a String",
    "topic": "Hashing",
    "pattern": "Hash Map",
    "difficulty": "Medium",
    "roiScore": 92,
    "probabilityScore": 90,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "find-all-anagrams-in-a-string",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/find-all-anagrams-in-a-string/",
    "neetCode": "",
    "day": 4,
    "isGap": false
  },
  {
    "id": 40,
    "problemName": "Group Anagrams",
    "topic": "Hashing",
    "pattern": "Hash Map",
    "difficulty": "Medium",
    "roiScore": 93,
    "probabilityScore": 91,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "group-anagrams",
    "gfg": "1",
    "codingNinjas": "group-anagrams",
    "interviewBit": "group-anagrams",
    "hackerRank": "group-anagrams",
    "takeUForward": "https://takeuforward.org/data-structure/group-anagrams/",
    "neetCode": "group-anagrams",
    "day": 5,
    "isGap": false
  },
  {
    "id": 56,
    "problemName": "Reverse String",
    "topic": "Strings",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 93,
    "probabilityScore": 83,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "reverse-string",
    "gfg": "1",
    "codingNinjas": "reverse-string",
    "interviewBit": "reverse-string",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/reverse-a-string/",
    "neetCode": "reverse-string",
    "day": 1,
    "isGap": false
  },
  {
    "id": 57,
    "problemName": "Valid Palindrome String",
    "topic": "Strings",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 94,
    "probabilityScore": 84,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "valid-palindrome",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/check-if-a-given-string-is-palindrome-or-not/",
    "neetCode": "",
    "day": 2,
    "isGap": false
  },
  {
    "id": 58,
    "problemName": "Longest Common Prefix",
    "topic": "Strings",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 95,
    "probabilityScore": 85,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "longest-common-prefix",
    "gfg": "1",
    "codingNinjas": "longest-common-prefix",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/longest-common-prefix-in-an-array/",
    "neetCode": "longest-common-prefix",
    "day": 3,
    "isGap": false
  },
  {
    "id": 59,
    "problemName": "Roman to Integer",
    "topic": "Strings",
    "pattern": "Math",
    "difficulty": "Easy",
    "roiScore": 96,
    "probabilityScore": 86,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "roman-to-integer",
    "gfg": "1",
    "codingNinjas": "roman-to-integer",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/roman-to-integer/",
    "neetCode": "",
    "day": 4,
    "isGap": false
  },
  {
    "id": 60,
    "problemName": "Integer to Roman",
    "topic": "Strings",
    "pattern": "Math",
    "difficulty": "Medium",
    "roiScore": 97,
    "probabilityScore": 87,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "integer-to-roman",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "integer-to-roman",
    "hackerRank": "integer-to-roman",
    "takeUForward": "https://takeuforward.org/data-structure/integer-to-roman/",
    "neetCode": "integer-to-roman",
    "day": 5,
    "isGap": false
  },
  {
    "id": 119,
    "problemName": "Valid Palindrome TP",
    "topic": "Two Pointer",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 92,
    "probabilityScore": 98,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "valid-palindrome",
    "gfg": "1",
    "codingNinjas": "valid-palindrome-tp",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/check-if-a-given-string-is-palindrome-or-not/",
    "neetCode": "",
    "day": 1,
    "isGap": false
  },
  {
    "id": 120,
    "problemName": "Two Sum II - Input Array Is Sorted",
    "topic": "Two Pointer",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 93,
    "probabilityScore": 75,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "two-sum-ii-input-array-is-sorted",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "two-sum-ii---input-array-is-sorted",
    "hackerRank": "two-sum-ii---input-array-is-sorted",
    "takeUForward": "https://takeuforward.org/data-structure/two-sum-ii-input-array-is-sorted/",
    "neetCode": "two-sum-ii---input-array-is-sorted",
    "day": 2,
    "isGap": false
  },
  {
    "id": 121,
    "problemName": "Remove Duplicates from Sorted Array",
    "topic": "Two Pointer",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 94,
    "probabilityScore": 76,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "remove-duplicates-from-sorted-array",
    "gfg": "1",
    "codingNinjas": "remove-duplicates-from-sorted-array",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/remove-duplicates-from-sorted-array/",
    "neetCode": "",
    "day": 3,
    "isGap": false
  },
  {
    "id": 122,
    "problemName": "3Sum TP",
    "topic": "Two Pointer",
    "pattern": "Two Pointer",
    "difficulty": "Medium",
    "roiScore": 95,
    "probabilityScore": 77,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "3sum",
    "gfg": "1",
    "codingNinjas": "3sum-tp",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-zero/",
    "neetCode": "3sum-tp",
    "day": 4,
    "isGap": false
  },
  {
    "id": 123,
    "problemName": "Container With Most Water TP",
    "topic": "Two Pointer",
    "pattern": "Two Pointer",
    "difficulty": "Medium",
    "roiScore": 96,
    "probabilityScore": 78,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "container-with-most-water",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/container-with-most-water/",
    "neetCode": "",
    "day": 5,
    "isGap": false
  },
  {
    "id": 101,
    "problemName": "Maximum Sum Subarray of Size K",
    "topic": "Sliding Window",
    "pattern": "Sliding Window",
    "difficulty": "Easy",
    "roiScore": 90,
    "probabilityScore": 80,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "maximum-average-subarray-i",
    "gfg": "1",
    "codingNinjas": "maximum-sum-subarray-of-size-k",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/maximum-sum-subarray-of-size-k/",
    "neetCode": "",
    "day": 1,
    "isGap": false
  },
  {
    "id": 102,
    "problemName": "Longest Substring Without Repeating Characters Sliding",
    "topic": "Sliding Window",
    "pattern": "Sliding Window",
    "difficulty": "Medium",
    "roiScore": 91,
    "probabilityScore": 81,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "longest-substring-without-repeating-characters",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/longest-substring-without-repeating-characters/",
    "neetCode": "longest-substring-without-repeating-characters-sliding",
    "day": 2,
    "isGap": false
  },
  {
    "id": 103,
    "problemName": "Longest Repeating Character Replacement",
    "topic": "Sliding Window",
    "pattern": "Sliding Window",
    "difficulty": "Medium",
    "roiScore": 92,
    "probabilityScore": 82,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "longest-repeating-character-replacement",
    "gfg": "1",
    "codingNinjas": "longest-repeating-character-replacement",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/longest-repeating-character-replacement/",
    "neetCode": "",
    "day": 3,
    "isGap": false
  },
  {
    "id": 104,
    "problemName": "Minimum Window Substring Sliding",
    "topic": "Sliding Window",
    "pattern": "Sliding Window",
    "difficulty": "Hard",
    "roiScore": 93,
    "probabilityScore": 83,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "minimum-window-substring",
    "gfg": "1",
    "codingNinjas": "minimum-window-substring-sliding",
    "interviewBit": "minimum-window-substring-sliding",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/minimum-window-substring/",
    "neetCode": "minimum-window-substring-sliding",
    "day": 4,
    "isGap": false
  },
  {
    "id": 76,
    "problemName": "Binary Search",
    "topic": "Binary Search",
    "pattern": "Binary Search",
    "difficulty": "Easy",
    "roiScore": 97,
    "probabilityScore": 79,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "binary-search",
    "gfg": "1",
    "codingNinjas": "binary-search",
    "interviewBit": "binary-search",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/binary-search-explained/",
    "neetCode": "binary-search",
    "day": 5,
    "isGap": false
  },
  {
    "id": 77,
    "problemName": "Search In Insert Position",
    "topic": "Binary Search",
    "pattern": "Binary Search",
    "difficulty": "Easy",
    "roiScore": 98,
    "probabilityScore": 80,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "search-insert-position",
    "gfg": "1",
    "codingNinjas": "search-in-insert-position",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/search-insert-position/",
    "neetCode": "",
    "day": 1,
    "isGap": false
  },
  {
    "id": 78,
    "problemName": "Find First and Last Position of Element in Sorted Array",
    "topic": "Binary Search",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "roiScore": 99,
    "probabilityScore": 81,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "find-first-and-last-position-of-element-in-sorted-array",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/first-and-last-occurrence-of-a-number-in-a-sorted-array/",
    "neetCode": "find-first-and-last-position-of-element-in-sorted-array",
    "day": 2,
    "isGap": false
  },
  {
    "id": 79,
    "problemName": "Search in Rotated Sorted Array",
    "topic": "Binary Search",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "roiScore": 100,
    "probabilityScore": 82,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "search-in-rotated-sorted-array",
    "gfg": "1",
    "codingNinjas": "search-in-rotated-sorted-array",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/search-in-rotated-sorted-array-i/",
    "neetCode": "",
    "day": 3,
    "isGap": false
  },
  {
    "id": 80,
    "problemName": "Search in Rotated Sorted Array II",
    "topic": "Binary Search",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "roiScore": 85,
    "probabilityScore": 83,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "search-in-rotated-sorted-array-ii",
    "gfg": "1",
    "codingNinjas": "search-in-rotated-sorted-array-ii",
    "interviewBit": "search-in-rotated-sorted-array-ii",
    "hackerRank": "search-in-rotated-sorted-array-ii",
    "takeUForward": "https://takeuforward.org/data-structure/search-in-a-rotated-sorted-array-ii/",
    "neetCode": "search-in-rotated-sorted-array-ii",
    "day": 4,
    "isGap": false
  },
  {
    "id": 154,
    "problemName": "Valid Parentheses",
    "topic": "Stack & Queue",
    "pattern": "Monotonic Stack",
    "difficulty": "Easy",
    "roiScore": 95,
    "probabilityScore": 85,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "valid-parentheses",
    "gfg": "1",
    "codingNinjas": "valid-parentheses",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/parenthesis-checker/",
    "neetCode": "valid-parentheses",
    "day": 5,
    "isGap": false
  },
  {
    "id": 155,
    "problemName": "Min Stack",
    "topic": "Stack & Queue",
    "pattern": "Monotonic Stack",
    "difficulty": "Medium",
    "roiScore": 96,
    "probabilityScore": 86,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "min-stack",
    "gfg": "1",
    "codingNinjas": "min-stack",
    "interviewBit": "",
    "hackerRank": "min-stack",
    "takeUForward": "https://takeuforward.org/data-structure/implement-min-stack-o1-space-complexity/",
    "neetCode": "",
    "day": 1,
    "isGap": false
  },
  {
    "id": 156,
    "problemName": "Implement Queue using Stacks",
    "topic": "Stack & Queue",
    "pattern": "Monotonic Stack",
    "difficulty": "Easy",
    "roiScore": 97,
    "probabilityScore": 87,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "implement-queue-using-stacks",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "implement-queue-using-stacks",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/implement-queue-using-stack/",
    "neetCode": "implement-queue-using-stacks",
    "day": 2,
    "isGap": false
  },
  {
    "id": 157,
    "problemName": "Implement Stack using Queues",
    "topic": "Stack & Queue",
    "pattern": "Monotonic Stack",
    "difficulty": "Easy",
    "roiScore": 98,
    "probabilityScore": 88,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "implement-stack-using-queues",
    "gfg": "1",
    "codingNinjas": "implement-stack-using-queues",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/implement-stack-using-single-queue/",
    "neetCode": "",
    "day": 3,
    "isGap": false
  },
  {
    "id": 134,
    "problemName": "Reverse Linked List",
    "topic": "Linked List",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 91,
    "probabilityScore": 89,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "reverse-linked-list",
    "gfg": "1",
    "codingNinjas": "reverse-linked-list",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/reverse-a-linked-list/",
    "neetCode": "reverse-linked-list",
    "day": 4,
    "isGap": false
  },
  {
    "id": 135,
    "problemName": "Linked List Cycle",
    "topic": "Linked List",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 92,
    "probabilityScore": 90,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "linked-list-cycle",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "linked-list-cycle",
    "takeUForward": "https://takeuforward.org/data-structure/detect-a-loop-in-in-a-linked-list/",
    "neetCode": "",
    "day": 5,
    "isGap": false
  },
  {
    "id": 136,
    "problemName": "Merge Two Sorted Lists",
    "topic": "Linked List",
    "pattern": "Two Pointer",
    "difficulty": "Easy",
    "roiScore": 93,
    "probabilityScore": 91,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "merge-two-sorted-lists",
    "gfg": "1",
    "codingNinjas": "merge-two-sorted-lists",
    "interviewBit": "merge-two-sorted-lists",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/merge-two-sorted-linked-lists/",
    "neetCode": "merge-two-sorted-lists",
    "day": 1,
    "isGap": false
  },
  {
    "id": 137,
    "problemName": "Remove Nth Node From End of List",
    "topic": "Linked List",
    "pattern": "Two Pointer",
    "difficulty": "Medium",
    "roiScore": 94,
    "probabilityScore": 92,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "remove-nth-node-from-end-of-list",
    "gfg": "1",
    "codingNinjas": "remove-nth-node-from-end-of-list",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/remove-nth-node-from-the-end-of-a-linked-list/",
    "neetCode": "",
    "day": 2,
    "isGap": false
  },
  {
    "id": 199,
    "problemName": "Binary Tree Inorder Traversal",
    "topic": "Binary Trees",
    "pattern": "Tree Traversal",
    "difficulty": "Easy",
    "roiScore": 92,
    "probabilityScore": 82,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "binary-tree-inorder-traversal",
    "gfg": "1",
    "codingNinjas": "binary-tree-inorder-traversal",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/inorder-traversal-of-binary-tree/",
    "neetCode": "",
    "day": 3,
    "isGap": false
  },
  {
    "id": 200,
    "problemName": "Binary Tree Preorder Traversal",
    "topic": "Binary Trees",
    "pattern": "Tree Traversal",
    "difficulty": "Easy",
    "roiScore": 93,
    "probabilityScore": 83,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "binary-tree-preorder-traversal",
    "gfg": "1",
    "codingNinjas": "binary-tree-preorder-traversal",
    "interviewBit": "binary-tree-preorder-traversal",
    "hackerRank": "binary-tree-preorder-traversal",
    "takeUForward": "https://takeuforward.org/data-structure/preorder-traversal-of-binary-tree/",
    "neetCode": "binary-tree-preorder-traversal",
    "day": 4,
    "isGap": false
  },
  {
    "id": 201,
    "problemName": "Binary Tree Postorder Traversal",
    "topic": "Binary Trees",
    "pattern": "Tree Traversal",
    "difficulty": "Easy",
    "roiScore": 94,
    "probabilityScore": 84,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "binary-tree-postorder-traversal",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/postorder-traversal-of-binary-tree/",
    "neetCode": "",
    "day": 5,
    "isGap": false
  },
  {
    "id": 202,
    "problemName": "Binary Tree Level Order Traversal",
    "topic": "Binary Trees",
    "pattern": "BFS",
    "difficulty": "Medium",
    "roiScore": 95,
    "probabilityScore": 85,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "binary-tree-level-order-traversal",
    "gfg": "1",
    "codingNinjas": "binary-tree-level-order-traversal",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/level-order-traversal-of-binary-tree/",
    "neetCode": "binary-tree-level-order-traversal",
    "day": 1,
    "isGap": false
  },
  {
    "id": 179,
    "problemName": "N meetings in one room",
    "topic": "Greedy",
    "pattern": "Greedy Interval",
    "difficulty": "Easy",
    "roiScore": 88,
    "probabilityScore": 86,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "non-overlapping-intervals",
    "gfg": "1",
    "codingNinjas": "n-meetings-in-one-room",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/n-meetings-in-one-room/",
    "neetCode": "",
    "day": 2,
    "isGap": false
  },
  {
    "id": 180,
    "problemName": "Activity Selection",
    "topic": "Greedy",
    "pattern": "Greedy Interval",
    "difficulty": "Easy",
    "roiScore": 89,
    "probabilityScore": 87,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "non-overlapping-intervals",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "activity-selection",
    "hackerRank": "activity-selection",
    "takeUForward": "https://takeuforward.org/data-structure/activity-selection-problem/",
    "neetCode": "activity-selection",
    "day": 3,
    "isGap": false
  },
  {
    "id": 181,
    "problemName": "Job Sequencing Problem",
    "topic": "Greedy",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "roiScore": 90,
    "probabilityScore": 88,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "course-schedule-iii",
    "gfg": "1",
    "codingNinjas": "job-sequencing-problem",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/job-sequencing-problem/",
    "neetCode": "",
    "day": 4,
    "isGap": false
  },
  {
    "id": 182,
    "problemName": "Fractional Knapsack",
    "topic": "Greedy",
    "pattern": "Greedy",
    "difficulty": "Easy",
    "roiScore": 91,
    "probabilityScore": 89,
    "expectedTime": 30,
    "status": "Solved",
    "confidence": 4,
    "mistakes": "Off-by-one errors on index boundaries.",
    "notes": "Think about the optimal space-time trade-off.",
    "leetcode": "maximum-units-on-a-truck",
    "gfg": "1",
    "codingNinjas": "fractional-knapsack",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/",
    "neetCode": "fractional-knapsack",
    "day": 5,
    "isGap": false
  },
  {
    "id": 236,
    "problemName": "Kth Largest Element in an Array",
    "topic": "Heap",
    "pattern": "Heap",
    "difficulty": "Medium",
    "roiScore": 85,
    "probabilityScore": 74,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "kth-largest-element-in-an-array",
    "gfg": "1",
    "codingNinjas": "kth-largest-element-in-an-array",
    "interviewBit": "",
    "hackerRank": "kth-largest-element-in-an-array",
    "takeUForward": "https://takeuforward.org/data-structure/kth-largest-element-in-an-array/",
    "neetCode": "kth-largest-element-in-an-array",
    "day": 1,
    "isGap": true
  },
  {
    "id": 237,
    "problemName": "K Closest Points to Origin",
    "topic": "Heap",
    "pattern": "Heap",
    "difficulty": "Medium",
    "roiScore": 86,
    "probabilityScore": 75,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "k-closest-points-to-origin",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "k-closest-points-to-origin",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/k-closest-points-to-origin/",
    "neetCode": "",
    "day": 2,
    "isGap": true
  },
  {
    "id": 238,
    "problemName": "Top K Frequent Elements Heap",
    "topic": "Heap",
    "pattern": "Heap",
    "difficulty": "Medium",
    "roiScore": 87,
    "probabilityScore": 76,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "top-k-frequent-elements",
    "gfg": "1",
    "codingNinjas": "top-k-frequent-elements-heap",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/top-k-frequent-elements-in-array/",
    "neetCode": "top-k-frequent-elements-heap",
    "day": 3,
    "isGap": true
  },
  {
    "id": 224,
    "problemName": "Search in a Binary Search Tree",
    "topic": "BST",
    "pattern": "DFS",
    "difficulty": "Easy",
    "roiScore": 94,
    "probabilityScore": 91,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "search-in-a-binary-search-tree",
    "gfg": "1",
    "codingNinjas": "search-in-a-binary-search-tree",
    "interviewBit": "",
    "hackerRank": "search-in-a-binary-search-tree",
    "takeUForward": "https://takeuforward.org/data-structure/search-in-a-binary-search-tree-bst/",
    "neetCode": "search-in-a-binary-search-tree",
    "day": 4,
    "isGap": true
  },
  {
    "id": 225,
    "problemName": "Find Min/Max in BST",
    "topic": "BST",
    "pattern": "DFS",
    "difficulty": "Easy",
    "roiScore": 95,
    "probabilityScore": 92,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "minimum-absolute-difference-in-bst",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "find-min/max-in-bst",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/find-minimum-and-maximum-in-binary-search-tree/",
    "neetCode": "",
    "day": 5,
    "isGap": true
  },
  {
    "id": 226,
    "problemName": "Insert into a Binary Search Tree",
    "topic": "BST",
    "pattern": "DFS",
    "difficulty": "Medium",
    "roiScore": 96,
    "probabilityScore": 93,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "insert-into-a-binary-search-tree",
    "gfg": "1",
    "codingNinjas": "insert-into-a-binary-search-tree",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/insert-a-node-in-binary-search-tree/",
    "neetCode": "insert-into-a-binary-search-tree",
    "day": 1,
    "isGap": true
  },
  {
    "id": 248,
    "problemName": "Breadth First Search (BFS)",
    "topic": "Graphs",
    "pattern": "BFS",
    "difficulty": "Easy",
    "roiScore": 97,
    "probabilityScore": 86,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "clone-graph",
    "gfg": "1",
    "codingNinjas": "breadth-first-search-bfs",
    "interviewBit": "",
    "hackerRank": "breadth-first-search-bfs",
    "takeUForward": "https://takeuforward.org/graph/bfs-traversal-in-graph/",
    "neetCode": "breadth-first-search-bfs",
    "day": 2,
    "isGap": true
  },
  {
    "id": 249,
    "problemName": "Depth First Search (DFS)",
    "topic": "Graphs",
    "pattern": "DFS",
    "difficulty": "Easy",
    "roiScore": 98,
    "probabilityScore": 87,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "clone-graph",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "depth-first-search-dfs",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/graph/depth-first-search-dfs-traversal-in-graph/",
    "neetCode": "",
    "day": 3,
    "isGap": true
  },
  {
    "id": 250,
    "problemName": "Number of Islands",
    "topic": "Graphs",
    "pattern": "DFS",
    "difficulty": "Medium",
    "roiScore": 99,
    "probabilityScore": 88,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "number-of-islands",
    "gfg": "1",
    "codingNinjas": "number-of-islands",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/number-of-islands/",
    "neetCode": "number-of-islands",
    "day": 4,
    "isGap": true
  },
  {
    "id": 251,
    "problemName": "Clone Graph",
    "topic": "Graphs",
    "pattern": "BFS",
    "difficulty": "Medium",
    "roiScore": 100,
    "probabilityScore": 89,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "clone-graph",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/clone-graph/",
    "neetCode": "",
    "day": 5,
    "isGap": true
  },
  {
    "id": 252,
    "problemName": "Course Schedule",
    "topic": "Graphs",
    "pattern": "DFS",
    "difficulty": "Medium",
    "roiScore": 80,
    "probabilityScore": 90,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "course-schedule",
    "gfg": "1",
    "codingNinjas": "course-schedule",
    "interviewBit": "course-schedule",
    "hackerRank": "course-schedule",
    "takeUForward": "https://takeuforward.org/graph/detect-cycle-in-a-directed-graph-using-dfs-graph-colouring/",
    "neetCode": "course-schedule",
    "day": 1,
    "isGap": true
  },
  {
    "id": 268,
    "problemName": "Climbing Stairs",
    "topic": "Dynamic Programming",
    "pattern": "Knapsack",
    "difficulty": "Easy",
    "roiScore": 96,
    "probabilityScore": 77,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "climbing-stairs",
    "gfg": "1",
    "codingNinjas": "climbing-stairs",
    "interviewBit": "",
    "hackerRank": "climbing-stairs",
    "takeUForward": "https://takeuforward.org/data-structure/dynamic-programming-climbing-stairs/",
    "neetCode": "climbing-stairs",
    "day": 2,
    "isGap": true
  },
  {
    "id": 269,
    "problemName": "House Robber",
    "topic": "Dynamic Programming",
    "pattern": "Knapsack",
    "difficulty": "Medium",
    "roiScore": 97,
    "probabilityScore": 78,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "house-robber",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/maximum-sum-of-non-adjacent-elements-dp-5/",
    "neetCode": "",
    "day": 3,
    "isGap": true
  },
  {
    "id": 270,
    "problemName": "House Robber II",
    "topic": "Dynamic Programming",
    "pattern": "Knapsack",
    "difficulty": "Medium",
    "roiScore": 98,
    "probabilityScore": 79,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "house-robber-ii",
    "gfg": "1",
    "codingNinjas": "house-robber-ii",
    "interviewBit": "house-robber-ii",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/dynamic-programming-house-robber-ii-dp-6/",
    "neetCode": "house-robber-ii",
    "day": 4,
    "isGap": true
  },
  {
    "id": 271,
    "problemName": "Coin Change",
    "topic": "Dynamic Programming",
    "pattern": "Knapsack",
    "difficulty": "Medium",
    "roiScore": 99,
    "probabilityScore": 80,
    "expectedTime": 35,
    "status": "Not Started",
    "confidence": 0,
    "mistakes": "",
    "notes": "",
    "leetcode": "coin-change",
    "gfg": "1",
    "codingNinjas": "",
    "interviewBit": "",
    "hackerRank": "",
    "takeUForward": "https://takeuforward.org/data-structure/coin-change-2-dp-22/",
    "neetCode": "",
    "day": 5,
    "isGap": true
  }
];
