export interface InfosysV2Problem {
  id: number;
  problemName: string;
  pattern: string; // One of the 25 primary pattern sections
  subPattern: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Very Hard';
  whyInfosysAsksThis: string;
  recognitionTrick: string;
  commonMistakes: string;
  timeComplexity: string;
  spaceComplexity: string;
  leetcode: string;
  gfg: string;
  codingNinjas: string;
  takeUForward: string;
  neetCode: string;
  striverVideo: string;
  companyTags: string[];
  frequency: number; // percentage (0-100)
  status: 'Not Started' | 'In Progress' | 'Solved' | 'Mastered' | 'Need Revision';
  confidence: number; // 1 to 5
  bookmarked?: boolean;
  notes?: string;
  approach?: string;
  expectedTime: number; // minutes
  solveTime?: number;
  lastAttempted?: string;
}

export interface PatternMeta {
  id: string;
  name: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Mixed';
  infosysFrequency: 'Extreme' | 'Very High' | 'High' | 'Medium';
  campusFrequency: string; // e.g. "95%"
  estimatedProbability: string; // e.g. "92%"
  recommendedTime: string; // e.g. "25 mins"
  totalProblems: number;
  subPatterns: string[];
}

export interface OAExperienceEntry {
  id: string;
  date: string;
  college: string;
  role: 'SP' | 'DSE' | 'Both';
  title: string;
  description: string;
  extractedPattern: string;
  extractedDifficulty: 'Easy' | 'Medium' | 'Hard' | 'Very Hard';
  similarProblemName: string;
  verifiedInDrive: boolean;
}

export const PATTERNS_LIST: PatternMeta[] = [
  {
    id: 'arrays',
    name: '1. Arrays',
    difficulty: 'Easy',
    infosysFrequency: 'Extreme',
    campusFrequency: '98%',
    estimatedProbability: '95%',
    recommendedTime: '15 mins',
    totalProblems: 18,
    subPatterns: ['Subarray Sweep', 'Prefix Sum Variant', 'Matrix Traversal', 'In-Place Rearrangement', 'Kadane Derivative']
  },
  {
    id: 'hashmap',
    name: '2. HashMap',
    difficulty: 'Easy',
    infosysFrequency: 'Extreme',
    campusFrequency: '96%',
    estimatedProbability: '94%',
    recommendedTime: '20 mins',
    totalProblems: 12,
    subPatterns: ['Frequency Counter', 'Index Pair Lookup', 'Subarray Target Match', 'Group Anagram Mapping']
  },
  {
    id: 'strings',
    name: '3. Strings',
    difficulty: 'Easy',
    infosysFrequency: 'Extreme',
    campusFrequency: '95%',
    estimatedProbability: '92%',
    recommendedTime: '20 mins',
    totalProblems: 15,
    subPatterns: ['Palindrome Expansion', 'Pattern Parsing', 'Character Frequency Match', 'String Transformation']
  },
  {
    id: 'two-pointer',
    name: '4. Two Pointer',
    difficulty: 'Medium',
    infosysFrequency: 'Very High',
    campusFrequency: '92%',
    estimatedProbability: '89%',
    recommendedTime: '22 mins',
    totalProblems: 12,
    subPatterns: ['Opposite Ends Converge', 'Fast & Slow Pointers', 'Container Boundaries', 'Three Sum Sweep']
  },
  {
    id: 'sliding-window',
    name: '5. Sliding Window',
    difficulty: 'Medium',
    infosysFrequency: 'Extreme',
    campusFrequency: '94%',
    estimatedProbability: '91%',
    recommendedTime: '25 mins',
    totalProblems: 16,
    subPatterns: ['Fixed Window Size K', 'Dynamic Window Expansion/Shrink', 'Exact At Most K Unique', 'Maximum Subarray Window']
  },
  {
    id: 'prefix-sum',
    name: '6. Prefix Sum',
    difficulty: 'Medium',
    infosysFrequency: 'Very High',
    campusFrequency: '90%',
    estimatedProbability: '88%',
    recommendedTime: '20 mins',
    totalProblems: 10,
    subPatterns: ['Cumulative Sum Lookup', 'Difference Array Technique', 'Subarray Divisible Sum', '2D Matrix Prefix']
  },
  {
    id: 'binary-search',
    name: '7. Binary Search',
    difficulty: 'Medium',
    infosysFrequency: 'Extreme',
    campusFrequency: '93%',
    estimatedProbability: '90%',
    recommendedTime: '25 mins',
    totalProblems: 15,
    subPatterns: ['Search in Rotated Sorted Array', 'Binary Search on Answer Range', 'Min-Max Capacity Allocation', 'Kth Element Search']
  },
  {
    id: 'sorting',
    name: '8. Sorting',
    difficulty: 'Easy',
    infosysFrequency: 'High',
    campusFrequency: '85%',
    estimatedProbability: '82%',
    recommendedTime: '18 mins',
    totalProblems: 8,
    subPatterns: ['Custom Comparator', 'Interval Sorting', 'Bucket/Counting Sort', 'Dutch National Flag Partition']
  },
  {
    id: 'stack',
    name: '9. Stack',
    difficulty: 'Medium',
    infosysFrequency: 'Very High',
    campusFrequency: '89%',
    estimatedProbability: '86%',
    recommendedTime: '20 mins',
    totalProblems: 16,
    subPatterns: ['Parentheses Matching', 'Expression Evaluation (RPN)', 'Simulation Queue/Stack', 'Min/Max Stack Tracking']
  },
  {
    id: 'queue',
    name: '10. Queue',
    difficulty: 'Easy',
    infosysFrequency: 'High',
    campusFrequency: '82%',
    estimatedProbability: '80%',
    recommendedTime: '18 mins',
    totalProblems: 8,
    subPatterns: ['Circular Queue Buffer', 'First Non-Repeating Stream', 'Sliding Window Queue', 'Simulation Sweep']
  },
  {
    id: 'monotonic-stack',
    name: '11. Monotonic Stack',
    difficulty: 'Hard',
    infosysFrequency: 'Very High',
    campusFrequency: '88%',
    estimatedProbability: '85%',
    recommendedTime: '30 mins',
    totalProblems: 10,
    subPatterns: ['Next Greater/Smaller Element', 'Histogram Area Bounds', 'Subarray Min/Max Sum Contribution', 'Stock Span']
  },
  {
    id: 'linked-list',
    name: '12. Linked List',
    difficulty: 'Medium',
    infosysFrequency: 'High',
    campusFrequency: '84%',
    estimatedProbability: '81%',
    recommendedTime: '22 mins',
    totalProblems: 10,
    subPatterns: ['Pointer Reversal', 'Cycle Detection (Floyd)', 'K-Group Reversal', 'Deep Copy with Random Pointers']
  },
  {
    id: 'trees',
    name: '13. Trees',
    difficulty: 'Medium',
    infosysFrequency: 'Very High',
    campusFrequency: '91%',
    estimatedProbability: '87%',
    recommendedTime: '25 mins',
    totalProblems: 11,
    subPatterns: ['Level Order BFS', 'Recursive DFS Traversal', 'Tree Diameter & Height', 'Lowest Common Ancestor (LCA)', 'Tree Serialization']
  },
  {
    id: 'bst',
    name: '14. BST',
    difficulty: 'Medium',
    infosysFrequency: 'High',
    campusFrequency: '83%',
    estimatedProbability: '80%',
    recommendedTime: '22 mins',
    totalProblems: 6,
    subPatterns: ['BST Validation', 'Kth Smallest / Inorder Walk', 'BST Search & Insertion', 'LCA in BST']
  },
  {
    id: 'heap',
    name: '15. Heap',
    difficulty: 'Medium',
    infosysFrequency: 'Very High',
    campusFrequency: '89%',
    estimatedProbability: '86%',
    recommendedTime: '25 mins',
    totalProblems: 8,
    subPatterns: ['Kth Largest/Smallest Element', 'Top K Frequent Elements', 'Two Heaps for Dynamic Median', 'Interval Task Scheduling']
  },
  {
    id: 'greedy',
    name: '16. Greedy',
    difficulty: 'Medium',
    infosysFrequency: 'Extreme',
    campusFrequency: '94%',
    estimatedProbability: '91%',
    recommendedTime: '22 mins',
    totalProblems: 10,
    subPatterns: ['Activity Selection', 'Gas Station Circuit', 'Jump Game Min Reach', 'Fractional Optimization']
  },
  {
    id: 'interval-problems',
    name: '17. Interval Problems',
    difficulty: 'Medium',
    infosysFrequency: 'Extreme',
    campusFrequency: '95%',
    estimatedProbability: '92%',
    recommendedTime: '25 mins',
    totalProblems: 8,
    subPatterns: ['Interval Merging', 'Meeting Room Conflicts', 'Non-overlapping Erasure', 'Interval Intersection']
  },
  {
    id: 'graph',
    name: '18. Graph',
    difficulty: 'Hard',
    infosysFrequency: 'Extreme',
    campusFrequency: '97%',
    estimatedProbability: '94%',
    recommendedTime: '35 mins',
    totalProblems: 15,
    subPatterns: ['BFS Grid Traversal', 'DFS Connected Components', 'Topological Sort (Kahn / Course Schedule)', 'Disjoint Set Union (DSU)', 'Cycle Detection in Directed/Undirected', 'Shortest Path (Dijkstra/BFS)']
  },
  {
    id: 'dynamic-programming',
    name: '19. Dynamic Programming',
    difficulty: 'Hard',
    infosysFrequency: 'Extreme',
    campusFrequency: '98%',
    estimatedProbability: '96%',
    recommendedTime: '35 mins',
    totalProblems: 25,
    subPatterns: ['1D DP (House Robber / Stairs)', 'Grid Path DP', '0/1 & Unbounded Knapsack', 'Longest Common Subsequence (LCS)', 'Longest Increasing Subsequence (LIS)', 'Partition DP', 'State / Stock DP']
  },
  {
    id: 'backtracking',
    name: '20. Backtracking',
    difficulty: 'Hard',
    infosysFrequency: 'High',
    campusFrequency: '86%',
    estimatedProbability: '83%',
    recommendedTime: '30 mins',
    totalProblems: 12,
    subPatterns: ['Subsets & Permutations Generator', 'Combination Sum Variants', 'Word Search Grid', 'N-Queens & Sudoku Constraints']
  },
  {
    id: 'recursion',
    name: '21. Recursion',
    difficulty: 'Easy',
    infosysFrequency: 'High',
    campusFrequency: '84%',
    estimatedProbability: '81%',
    recommendedTime: '20 mins',
    totalProblems: 8,
    subPatterns: ['Recursive Parentheses Generator', 'Divide & Conquer Power Calculation', 'Tower of Hanoi & Josephus', 'Stack Reversal with Recursion']
  },
  {
    id: 'bit-manipulation',
    name: '22. Bit Manipulation',
    difficulty: 'Medium',
    infosysFrequency: 'High',
    campusFrequency: '87%',
    estimatedProbability: '84%',
    recommendedTime: '20 mins',
    totalProblems: 11,
    subPatterns: ['Single Number XOR Cancellation', 'Bit Count & Power of 2', 'Bitwise Range Operations', 'Max XOR Pair Trie']
  },
  {
    id: 'design-questions',
    name: '23. Design Questions',
    difficulty: 'Hard',
    infosysFrequency: 'Very High',
    campusFrequency: '89%',
    estimatedProbability: '86%',
    recommendedTime: '35 mins',
    totalProblems: 10,
    subPatterns: ['LRU Cache (HashMap + Doubly LinkedList)', 'LFU Cache', 'Custom HashMap & HashSet Design', 'Min Stack & Circular Queue', 'Trie Dictionary']
  },
  {
    id: 'math',
    name: '24. Math',
    difficulty: 'Easy',
    infosysFrequency: 'High',
    campusFrequency: '85%',
    estimatedProbability: '82%',
    recommendedTime: '18 mins',
    totalProblems: 12,
    subPatterns: ['Sieve of Eratosthenes', 'GCD & Euclidean Algorithm', 'Modular Exponentiation', 'Pascal Triangle & Combinatorics']
  },
  {
    id: 'sql',
    name: '25. SQL',
    difficulty: 'Easy',
    infosysFrequency: 'Very High',
    campusFrequency: '92%',
    estimatedProbability: '89%',
    recommendedTime: '15 mins',
    totalProblems: 11,
    subPatterns: ['Nth Highest Salary / Window Functions', 'Self-Joins & Manager Lookup', 'Group By & Having Aggregation', 'Duplicate & Tree Node Processing']
  }
];

export const INITIAL_PROBLEMS_V2: InfosysV2Problem[] = [
  // 1. ARRAYS
  {
    id: 101,
    problemName: 'Two Sum',
    pattern: '1. Arrays',
    subPattern: 'Index Pair Lookup',
    difficulty: 'Easy',
    whyInfosysAsksThis: 'Primary screener question in Infosys DSE & SP round 1 to check map hashing efficiency.',
    recognitionTrick: 'Find two items in array sum up to target T in single linear pass.',
    commonMistakes: 'Reusing the same element twice (e.g. nums[i] + nums[i] = target).',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/two-sum/',
    gfg: 'https://www.geeksforgeeks.org/problems/two-sum/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/two-sum',
    takeUForward: 'https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/',
    neetCode: 'https://neetcode.io/problems/two-integer-sum',
    striverVideo: 'https://www.youtube.com/watch?v=UXDSeD9mN-k',
    companyTags: ['Infosys DSE', 'Infosys SP', 'Vardhaman Drive'],
    frequency: 95,
    status: 'Solved',
    confidence: 5,
    expectedTime: 15,
    approach: 'Maintain a hashmap storing value -> index. For each element num, check if target - num exists in map.'
  },
  {
    id: 102,
    problemName: 'Best Time to Buy and Sell Stock',
    pattern: '1. Arrays',
    subPattern: 'Kadane Derivative',
    difficulty: 'Easy',
    whyInfosysAsksThis: 'Tests single-pass min-value tracking and maximum difference logic.',
    recognitionTrick: 'Maximize price difference prices[j] - prices[i] where j > i.',
    commonMistakes: 'Using nested loops (O(N^2)) leading to Time Limit Exceeded.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    gfg: 'https://www.geeksforgeeks.org/problems/buy-stock-2/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/stocks-are-profitable',
    takeUForward: 'https://takeuforward.org/data-structure/stock-buy-and-sell/',
    neetCode: 'https://neetcode.io/problems/buy-and-sell-crypto',
    striverVideo: 'https://www.youtube.com/watch?v=eMSfBgbiESc',
    companyTags: ['Infosys DSE', 'Infosys SP'],
    frequency: 94,
    status: 'Solved',
    confidence: 5,
    expectedTime: 15,
    approach: 'Track minimum price seen so far minPrice and maximum profit max(maxProfit, price - minPrice).'
  },
  {
    id: 103,
    problemName: 'Product of Array Except Self',
    pattern: '1. Arrays',
    subPattern: 'Prefix & Suffix Product',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Frequent in Infosys OA story questions where division operator is explicitly forbidden.',
    recognitionTrick: 'Calculate output[i] equal to product of all elements except nums[i] without using division.',
    commonMistakes: 'Trying to divide by total product without handling zero values.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/product-of-array-except-self/',
    gfg: 'https://www.geeksforgeeks.org/problems/product-array-puzzle4522/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/product-of-array-except-self',
    takeUForward: 'https://takeuforward.org/data-structure/product-of-array-except-self/',
    neetCode: 'https://neetcode.io/problems/products-of-array-discluding-self',
    striverVideo: 'https://www.youtube.com/watch?v=gREVHiZPXeQ',
    companyTags: ['Infosys SP', 'Infytq'],
    frequency: 92,
    status: 'Solved',
    confidence: 4,
    expectedTime: 20,
    approach: 'Compute prefix products in output array in left-to-right pass, then multiply by running right suffix product.'
  },
  {
    id: 104,
    problemName: 'Maximum Subarray (Kadane Algorithm)',
    pattern: '1. Arrays',
    subPattern: 'Kadane Derivative',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Classic core algorithm tested in Infosys SP L1 round.',
    recognitionTrick: 'Find contiguous subarray with largest sum in dynamic list.',
    commonMistakes: 'Resetting current sum to 0 instead of resetting to current element when current sum < 0.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/maximum-subarray/',
    gfg: 'https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/maximum-subarray-sum',
    takeUForward: 'https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/',
    neetCode: 'https://neetcode.io/problems/maximum-subarray',
    striverVideo: 'https://www.youtube.com/watch?v=AHZpyENo7kE',
    companyTags: ['Infosys SP', 'Infosys DSE'],
    frequency: 96,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 15,
    approach: 'Keep currSum = max(num, currSum + num) and maxOverall = max(maxOverall, currSum).'
  },
  {
    id: 105,
    problemName: 'Rotate Array',
    pattern: '1. Arrays',
    subPattern: 'In-Place Rearrangement',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Tests array boundary handling and in-place reversal tricks.',
    recognitionTrick: 'Shift array right by k steps in O(1) extra space.',
    commonMistakes: 'Not doing k = k % n when k > n.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/rotate-array/',
    gfg: 'https://www.geeksforgeeks.org/problems/rotate-array-by-n-elements-1587115621/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/rotate-array',
    takeUForward: 'https://takeuforward.org/data-structure/rotate-array-by-k-elements/',
    neetCode: 'https://neetcode.io/problems/rotate-array',
    striverVideo: 'https://www.youtube.com/watch?v=wvcQg43_V8U',
    companyTags: ['Infosys DSE'],
    frequency: 88,
    status: 'Solved',
    confidence: 4,
    expectedTime: 18,
    approach: 'Reverse entire array, reverse first k elements, then reverse remaining n - k elements.'
  },
  {
    id: 106,
    problemName: 'Trapping Rain Water',
    pattern: '1. Arrays',
    subPattern: 'Two Pointer Boundary',
    difficulty: 'Hard',
    whyInfosysAsksThis: 'Benchmark question for Infosys SP L2/L3 role shortlisting.',
    recognitionTrick: 'Calculate trapped unit volume bounded by heights array.',
    commonMistakes: 'Not taking minimum of leftMax and rightMax before subtracting current height.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/trapping-rain-water/',
    gfg: 'https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/trapping-rain-water',
    takeUForward: 'https://takeuforward.org/data-structure/trapping-rainwater/',
    neetCode: 'https://neetcode.io/problems/trapping-rain-water',
    striverVideo: 'https://www.youtube.com/watch?v=m18Hntz4go8',
    companyTags: ['Infosys SP', 'HackWithInfy'],
    frequency: 93,
    status: 'In Progress',
    confidence: 3,
    expectedTime: 30,
    approach: 'Use two pointers left=0, right=n-1 and maintain maxLeft and maxRight. Move pointer pointing to smaller max height.'
  },

  // 2. HASHMAP
  {
    id: 201,
    problemName: 'Group Anagrams',
    pattern: '2. HashMap',
    subPattern: 'Group Anagram Mapping',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Extremely popular in Infosys OA story questions involving string grouping and inventory categorization.',
    recognitionTrick: 'Group strings that share the exact same character counts.',
    commonMistakes: 'Using string sorting as key when character frequency array tuple as key is faster O(N * K).',
    timeComplexity: 'O(N * K log K)',
    spaceComplexity: 'O(N * K)',
    leetcode: 'https://leetcode.com/problems/group-anagrams/',
    gfg: 'https://www.geeksforgeeks.org/problems/print-anagrams-together/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/group-anagrams',
    takeUForward: 'https://takeuforward.org/data-structure/group-anagrams/',
    neetCode: 'https://neetcode.io/problems/anagram-groups',
    striverVideo: 'https://www.youtube.com/watch?v=0I6IL3Rus34',
    companyTags: ['Infosys SP', 'Infosys DSE'],
    frequency: 94,
    status: 'Solved',
    confidence: 4,
    expectedTime: 20,
    approach: 'Create a HashMap with sorted string (or char frequency tuple) as key and array of anagrams as value.'
  },
  {
    id: 202,
    problemName: 'Subarray Sum Equals K',
    pattern: '2. HashMap',
    subPattern: 'Subarray Target Match',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Core problem combining Prefix Sum with HashMap count lookup.',
    recognitionTrick: 'Count contiguous subarrays summing to target K in negative/positive array.',
    commonMistakes: 'Trying to use Sliding Window when negative numbers exist in array.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/subarray-sum-equals-k/',
    gfg: 'https://www.geeksforgeeks.org/problems/subarrays-with-sum-k/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/subarrays-with-sum-k',
    takeUForward: 'https://takeuforward.org/data-structure/count-subarray-sum-equals-k/',
    neetCode: 'https://neetcode.io/problems/subarray-sum-equals-k',
    striverVideo: 'https://www.youtube.com/watch?v=xvN1GFsh4ow',
    companyTags: ['Infosys SP', 'HackWithInfy'],
    frequency: 96,
    status: 'Solved',
    confidence: 4,
    expectedTime: 22,
    approach: 'Maintain running prefixSum and map storing prefixSum frequencies. Add count of (prefixSum - k) to answer.'
  },

  // 3. STRINGS
  {
    id: 301,
    problemName: 'Longest Palindromic Substring',
    pattern: '3. Strings',
    subPattern: 'Palindrome Expansion',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Tests center expansion approach and boundary checks.',
    recognitionTrick: 'Find longest contiguous substring that reads identical backwards.',
    commonMistakes: 'Forgetting to check even-length palindrome centers (expandAroundCenter(i, i+1)).',
    timeComplexity: 'O(N^2)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/longest-palindromic-substring/',
    gfg: 'https://www.geeksforgeeks.org/problems/longest-palindrome-in-a-string3411/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/longest-palindromic-substring',
    takeUForward: 'https://takeuforward.org/data-structure/longest-palindromic-substring/',
    neetCode: 'https://neetcode.io/problems/longest-palindromic-substring',
    striverVideo: 'https://www.youtube.com/watch?v=XYQecbcd6_c',
    companyTags: ['Infosys SP', 'Vardhaman Drive'],
    frequency: 91,
    status: 'Solved',
    confidence: 4,
    expectedTime: 25,
    approach: 'Iterate through every character i, expanding outward for odd center (i, i) and even center (i, i+1).'
  },

  // 4. TWO POINTER
  {
    id: 401,
    problemName: 'Container With Most Water',
    pattern: '4. Two Pointer',
    subPattern: 'Opposite Ends Converge',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Checks greedy choice property with two converging pointers.',
    recognitionTrick: 'Find two lines that contain max area min(h[l], h[r]) * (r - l).',
    commonMistakes: 'Moving the pointer with larger height instead of smaller height.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/container-with-most-water/',
    gfg: 'https://www.geeksforgeeks.org/problems/container-with-most-water8003/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/container-with-most-water',
    takeUForward: 'https://takeuforward.org/data-structure/container-with-most-water/',
    neetCode: 'https://neetcode.io/problems/max-water-container',
    striverVideo: 'https://www.youtube.com/watch?v=ZHQg07n6fD0',
    companyTags: ['Infosys SP', 'Infosys DSE'],
    frequency: 90,
    status: 'Solved',
    confidence: 5,
    expectedTime: 20,
    approach: 'Start left=0, right=n-1. Calculate current area. Always increment left pointer if height[left] < height[right], else decrement right.'
  },

  // 5. SLIDING WINDOW
  {
    id: 501,
    problemName: 'Longest Substring Without Repeating Characters',
    pattern: '5. Sliding Window',
    subPattern: 'Dynamic Window Expansion/Shrink',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Top 3 most asked sliding window questions in Infosys campus drives.',
    recognitionTrick: 'Find length of longest contiguous substring without duplicate characters.',
    commonMistakes: 'Not updating left window pointer to max(left, lastSeen[char] + 1).',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(min(N, M))',
    leetcode: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    gfg: 'https://www.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/longest-substring-without-repeating-characters',
    takeUForward: 'https://takeuforward.org/data-structure/length-of-longest-substring-without-any-repeating-character/',
    neetCode: 'https://neetcode.io/problems/longest-substring-without-duplicates',
    striverVideo: 'https://www.youtube.com/watch?v=qtVh-XEps60',
    companyTags: ['Infosys SP', 'Infosys DSE', 'Vardhaman Drive'],
    frequency: 98,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 20,
    approach: 'Maintain a hashmap of last seen char indices. Expand right pointer; if char seen inside current window, jump left pointer.'
  },
  {
    id: 502,
    problemName: 'Minimum Window Substring',
    pattern: '5. Sliding Window',
    subPattern: 'Dynamic Window Expansion/Shrink',
    difficulty: 'Hard',
    whyInfosysAsksThis: 'Frequently used in Infosys SP L2/L3 OA cutoff evaluations.',
    recognitionTrick: 'Find smallest substring in S containing all characters of string T.',
    commonMistakes: 'Shrinking window before match count satisfies required distinct counts.',
    timeComplexity: 'O(N + M)',
    spaceComplexity: 'O(M)',
    leetcode: 'https://leetcode.com/problems/minimum-window-substring/',
    gfg: 'https://www.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string-1587115621/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/minimum-window-substring',
    takeUForward: 'https://takeuforward.org/data-structure/minimum-window-substring/',
    neetCode: 'https://neetcode.io/problems/minimum-window-with-characters',
    striverVideo: 'https://www.youtube.com/watch?v=WJaij9ffOIY',
    companyTags: ['Infosys SP', 'HackWithInfy'],
    frequency: 92,
    status: 'In Progress',
    confidence: 3,
    expectedTime: 30,
    approach: 'Expand right pointer until all characters matched, then contract left pointer while maintaining match invariant to find min length.'
  },

  // 6. PREFIX SUM
  {
    id: 601,
    problemName: 'Continuous Subarray Sum',
    pattern: '6. Prefix Sum',
    subPattern: 'Subarray Divisible Sum',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Tests modular arithmetic combined with prefix sum map storage.',
    recognitionTrick: 'Check if array contains subarray of length >= 2 whose sum is multiple of k.',
    commonMistakes: 'Not storing remainder 0 with index -1 initially in map.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/continuous-subarray-sum/',
    gfg: 'https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/continuous-subarray-sum',
    takeUForward: 'https://takeuforward.org/data-structure/continuous-subarray-sum/',
    neetCode: 'https://neetcode.io/problems/continuous-subarray-sum',
    striverVideo: 'https://www.youtube.com/watch?v=OKcrNkc0MTU',
    companyTags: ['Infosys SP'],
    frequency: 89,
    status: 'Solved',
    confidence: 4,
    expectedTime: 22,
    approach: 'Store map remainder = prefixSum % k -> earliest index. If remainder reoccurs at index i where i - map[rem] >= 2, return true.'
  },

  // 7. BINARY SEARCH
  {
    id: 701,
    problemName: 'Search in Rotated Sorted Array',
    pattern: '7. Binary Search',
    subPattern: 'Search in Rotated Sorted Array',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'High-frequency question in Infosys SP L1 round.',
    recognitionTrick: 'Sorted array shifted at unknown pivot point; search target in O(log N).',
    commonMistakes: 'Not checking which half (left or right) is sorted before narrowing search range.',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    gfg: 'https://www.geeksforgeeks.org/problems/search-in-a-rotated-array0908/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/search-in-rotated-sorted-array',
    takeUForward: 'https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/',
    neetCode: 'https://neetcode.io/problems/find-target-in-rotated-sorted-array',
    striverVideo: 'https://www.youtube.com/watch?v=r3pMQ8-Ad5s',
    companyTags: ['Infosys SP', 'Infosys DSE'],
    frequency: 96,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 20,
    approach: 'At mid, determine if left half [low..mid] or right half [mid..high] is sorted, then check if target lies within sorted half.'
  },
  {
    id: 702,
    problemName: 'Koko Eating Bananas (BS on Answer)',
    pattern: '7. Binary Search',
    subPattern: 'Binary Search on Answer Range',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Classic Binary Search on Answer pattern heavily featured in Infosys OA story questions.',
    recognitionTrick: 'Find minimum rate speed K to finish task within H hours.',
    commonMistakes: 'Using integer division Math.floor instead of Math.ceil(pile / speed) for hour calculation.',
    timeComplexity: 'O(N log(maxPile))',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/koko-eating-bananas/',
    gfg: 'https://www.geeksforgeeks.org/problems/koko-eating-bananas/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/koko-eating-bananas',
    takeUForward: 'https://takeuforward.org/data-structure/koko-eating-bananas/',
    neetCode: 'https://neetcode.io/problems/eating-bananas',
    striverVideo: 'https://www.youtube.com/watch?v=qyfekrNni90',
    companyTags: ['Infosys SP', 'Infytq'],
    frequency: 93,
    status: 'Solved',
    confidence: 4,
    expectedTime: 25,
    approach: 'Set BS range [1, max(piles)]. For mid speed, calculate total hours. If hours <= H, store mid as answer and search lower half.'
  },

  // 11. MONOTONIC STACK
  {
    id: 1101,
    problemName: 'Daily Temperatures / Next Greater Element',
    pattern: '11. Monotonic Stack',
    subPattern: 'Next Greater Element',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Tests monotonic stack index retention for distance calculation.',
    recognitionTrick: 'For each index i, find distance to next index with greater value.',
    commonMistakes: 'Pushing values instead of indices onto the stack.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/daily-temperatures/',
    gfg: 'https://www.geeksforgeeks.org/problems/next-larger-element-1587115620/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/next-greater-element',
    takeUForward: 'https://takeuforward.org/data-structure/next-greater-element-using-stack/',
    neetCode: 'https://neetcode.io/problems/daily-temperatures',
    striverVideo: 'https://www.youtube.com/watch?v=7PrncD7v9YQ',
    companyTags: ['Infosys SP', 'Infosys DSE'],
    frequency: 91,
    status: 'Solved',
    confidence: 4,
    expectedTime: 20,
    approach: 'Maintain a stack of indices with decreasing temperatures. Pop indices while current temp > temp[stack.top()] and update result[top] = i - top.'
  },
  {
    id: 1102,
    problemName: 'Largest Rectangle in Histogram',
    pattern: '11. Monotonic Stack',
    subPattern: 'Histogram Area Bounds',
    difficulty: 'Hard',
    whyInfosysAsksThis: 'High-bar question in Infosys SP L2 / L3 hiring drives.',
    recognitionTrick: 'Find max rectangular area bounded by contiguous bar heights.',
    commonMistakes: 'Not pushing a pseudo height 0 at the end to flush out remaining stack bars.',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    gfg: 'https://www.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram-1587115620/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/largest-rectangle-in-histogram',
    takeUForward: 'https://takeuforward.org/data-structure/area-of-largest-rectangle-in-histogram/',
    neetCode: 'https://neetcode.io/problems/largest-rectangle-in-histogram',
    striverVideo: 'https://www.youtube.com/watch?v=X0X6G-eWgQ8',
    companyTags: ['Infosys SP', 'HackWithInfy'],
    frequency: 88,
    status: 'Need Revision',
    confidence: 3,
    expectedTime: 30,
    approach: 'Maintain monotonic increasing stack of bar indices. When a shorter bar is encountered, pop elements and calculate area using popped height and width.'
  },

  // 17. INTERVAL PROBLEMS
  {
    id: 1701,
    problemName: 'Merge Intervals',
    pattern: '17. Interval Problems',
    subPattern: 'Interval Merging',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Appears in over 40% of Infosys SP round 1 test sets.',
    recognitionTrick: 'Given overlapping ranges [start, end], merge all intersecting intervals.',
    commonMistakes: 'Forgetting to sort intervals by start time first.',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/merge-intervals/',
    gfg: 'https://www.geeksforgeeks.org/problems/overlapping-intervals--170647/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/merge-overlapping-intervals',
    takeUForward: 'https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/',
    neetCode: 'https://neetcode.io/problems/merge-intervals',
    striverVideo: 'https://www.youtube.com/watch?v=IexN60k62jo',
    companyTags: ['Infosys SP', 'Infosys DSE', 'Vardhaman Drive'],
    frequency: 97,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 20,
    approach: 'Sort intervals by start time. Iterate through intervals; if current start <= previous end, merge by updating end = max(prev.end, curr.end).'
  },

  // 18. GRAPH
  {
    id: 1801,
    problemName: 'Number of Islands (Grid BFS/DFS)',
    pattern: '18. Graph',
    subPattern: 'Grid BFS/DFS Traversal',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'The single most frequent graph question asked in Infosys SP OA history.',
    recognitionTrick: 'Count connected components of 1s in 2D binary grid.',
    commonMistakes: 'Not marking visited cells in place or forgetting out-of-bound grid checks.',
    timeComplexity: 'O(R * C)',
    spaceComplexity: 'O(R * C)',
    leetcode: 'https://leetcode.com/problems/number-of-islands/',
    gfg: 'https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/find-number-of-islands',
    takeUForward: 'https://takeuforward.org/data-structure/number-of-islands/',
    neetCode: 'https://neetcode.io/problems/count-number-of-islands',
    striverVideo: 'https://www.youtube.com/watch?v=muncqlKJ86w',
    companyTags: ['Infosys SP', 'Infosys DSE', 'Vardhaman Drive'],
    frequency: 99,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 20,
    approach: 'Iterate 2D grid. For every unvisited "1", increment count and run DFS/BFS to sink/mark all 4-directionally connected "1"s.'
  },
  {
    id: 1802,
    problemName: 'Course Schedule II (Topological Sort / Kahn)',
    pattern: '18. Graph',
    subPattern: 'Topological Sort (Kahn / Course Schedule)',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Essential dependency ordering problem frequently framed as project scheduling stories in Infosys OA.',
    recognitionTrick: 'Order tasks given prerequisite pairs or detect impossible cycle dependency.',
    commonMistakes: 'Not checking if output order length equals total nodes numCourses (indicating cycle).',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V + E)',
    leetcode: 'https://leetcode.com/problems/course-schedule-ii/',
    gfg: 'https://www.geeksforgeeks.org/problems/course-schedule/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/course-schedule-ii',
    takeUForward: 'https://takeuforward.org/data-structure/kahns-algorithm-topological-sort-bfs/',
    neetCode: 'https://neetcode.io/problems/course-schedule-ii',
    striverVideo: 'https://www.youtube.com/watch?v=WAOfKpxYHR8',
    companyTags: ['Infosys SP', 'HackWithInfy'],
    frequency: 94,
    status: 'Solved',
    confidence: 4,
    expectedTime: 25,
    approach: 'Build adjacency list and indegree array. Push nodes with indegree=0 into BFS queue. Pop node, append to topological result, decrement neighbor indegrees.'
  },
  {
    id: 1803,
    problemName: 'Redundant Connection (DSU / Union Find)',
    pattern: '18. Graph',
    subPattern: 'Disjoint Set Union (DSU)',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Standard Disjoint Set Union check to find the edge creating a cycle in network.',
    recognitionTrick: 'Identify edge that forms cycle when added to existing tree.',
    commonMistakes: 'Omitting path compression in find(i) or union by rank.',
    timeComplexity: 'O(N * alpha(N))',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/redundant-connection/',
    gfg: 'https://www.geeksforgeeks.org/problems/detect-cycle-using-dsu/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/redundant-connection',
    takeUForward: 'https://takeuforward.org/data-structure/disjoint-set-union-find-by-rank-union-by-size-path-compression-introduction/',
    neetCode: 'https://neetcode.io/problems/redundant-connection',
    striverVideo: 'https://www.youtube.com/watch?v=FXWRE67PLL0',
    companyTags: ['Infosys SP'],
    frequency: 91,
    status: 'Solved',
    confidence: 4,
    expectedTime: 25,
    approach: 'Initialize parent array. For each edge (u, v), if find(u) == find(v), this edge creates cycle and is redundant; otherwise union(u, v).'
  },

  // 19. DYNAMIC PROGRAMMING
  {
    id: 1901,
    problemName: 'Coin Change (Unbounded Knapsack)',
    pattern: '19. Dynamic Programming',
    subPattern: '0/1 & Unbounded Knapsack',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Most tested DP problem in Infosys SP OA exams.',
    recognitionTrick: 'Find minimum coins needed to make given target amount.',
    commonMistakes: 'Initializing DP array with 0 instead of infinity (Amount + 1).',
    timeComplexity: 'O(N * Amount)',
    spaceComplexity: 'O(Amount)',
    leetcode: 'https://leetcode.com/problems/coin-change/',
    gfg: 'https://www.geeksforgeeks.org/problems/coin-change2448/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/coin-change',
    takeUForward: 'https://takeuforward.org/data-structure/coin-change-2-dp-22/',
    neetCode: 'https://neetcode.io/problems/coin-change',
    striverVideo: 'https://www.youtube.com/watch?v=myPeWb3Y68A',
    companyTags: ['Infosys SP', 'Infytq'],
    frequency: 97,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 25,
    approach: 'dp[i] stores min coins for amount i. dp[i] = min(dp[i], 1 + dp[i - coin]) for all coin <= i.'
  },
  {
    id: 1902,
    problemName: 'Longest Increasing Subsequence (LIS)',
    pattern: '19. Dynamic Programming',
    subPattern: 'Longest Increasing Subsequence (LIS)',
    difficulty: 'Medium',
    whyInfosysAsksThis: 'Core benchmark for evaluating DP optimization capabilities.',
    recognitionTrick: 'Find maximum length of strictly increasing subsequence.',
    commonMistakes: 'Confusing subsequence (non-contiguous) with subarray (contiguous).',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    gfg: 'https://www.geeksforgeeks.org/problems/longest-increasing-subsequence-1587115620/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/longest-increasing-subsequence',
    takeUForward: 'https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/',
    neetCode: 'https://neetcode.io/problems/longest-increasing-subsequence',
    striverVideo: 'https://www.youtube.com/watch?v=on2hvxBXJH4',
    companyTags: ['Infosys SP', 'HackWithInfy'],
    frequency: 95,
    status: 'Solved',
    confidence: 4,
    expectedTime: 25,
    approach: 'Use DP array + Binary Search (Patience Sorting / std::lower_bound) to construct tails array in O(N log N).'
  },

  // 23. DESIGN QUESTIONS
  {
    id: 2301,
    problemName: 'LRU Cache Design',
    pattern: '23. Design Questions',
    subPattern: 'LRU Cache (HashMap + Doubly LinkedList)',
    difficulty: 'Hard',
    whyInfosysAsksThis: 'Premier object-oriented system design question in Infosys SP L3 technical interview.',
    recognitionTrick: 'Design cache with get and put in O(1) time complexity, evicting least recently used items when full.',
    commonMistakes: 'Not maintaining dummy head and tail nodes in Doubly LinkedList leading to null pointer exceptions.',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(Capacity)',
    leetcode: 'https://leetcode.com/problems/lru-cache/',
    gfg: 'https://www.geeksforgeeks.org/problems/lru-cache/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/lru-cache-implementation',
    takeUForward: 'https://takeuforward.org/data-structure/lru-cache-implementation/',
    neetCode: 'https://neetcode.io/problems/lru-cache',
    striverVideo: 'https://www.youtube.com/watch?v=xDEuM5qa0zg',
    companyTags: ['Infosys SP', 'Infosys L3 Interview'],
    frequency: 96,
    status: 'Solved',
    confidence: 4,
    expectedTime: 35,
    approach: 'Combine HashMap<key, Node> for O(1) lookup with Doubly LinkedList for O(1) node deletion and insertion at head.'
  },

  // 24. MATH
  {
    id: 2401,
    problemName: 'Count Primes (Sieve of Eratosthenes)',
    pattern: '24. Math',
    subPattern: 'Sieve of Eratosthenes',
    difficulty: 'Easy',
    whyInfosysAsksThis: 'Standard fast primality testing screening question in Infosys DSE round.',
    recognitionTrick: 'Count strictly less than N prime numbers efficiently.',
    commonMistakes: 'Iterating outer loop up to N instead of sqrt(N) in Sieve.',
    timeComplexity: 'O(N log log N)',
    spaceComplexity: 'O(N)',
    leetcode: 'https://leetcode.com/problems/count-primes/',
    gfg: 'https://www.geeksforgeeks.org/problems/sieve-of-eratosthenes5242/1',
    codingNinjas: 'https://www.naukri.com/code360/problems/prime-numbers-till-n',
    takeUForward: 'https://takeuforward.org/data-structure/sieve-of-eratosthenes-prime-numbers-in-a-range/',
    neetCode: 'https://neetcode.io/problems/count-primes',
    striverVideo: 'https://www.youtube.com/watch?v=g5Fyx6QcD5c',
    companyTags: ['Infosys DSE'],
    frequency: 87,
    status: 'Solved',
    confidence: 5,
    expectedTime: 15,
    approach: 'Initialize boolean array isPrime of size N with true. Mark multiples of prime p starting from p*p as false.'
  },

  // 25. SQL
  {
    id: 2501,
    problemName: 'Second Highest Salary (SQL Window / Subquery)',
    pattern: '25. SQL',
    subPattern: 'Nth Highest Salary / Window Functions',
    difficulty: 'Easy',
    whyInfosysAsksThis: 'Asked in almost 100% of Infosys technical interview database screening rounds.',
    recognitionTrick: 'Find 2nd highest value in table handling nulls if no 2nd highest exists.',
    commonMistakes: 'Forgetting DISTINCT keyword when multiple employees share the top salary.',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(1)',
    leetcode: 'https://leetcode.com/problems/second-highest-salary/',
    gfg: 'https://www.geeksforgeeks.org/problems/second-highest-salary-in-sql/',
    codingNinjas: 'https://www.naukri.com/code360/problems/second-highest-salary',
    takeUForward: 'https://takeuforward.org/sql/second-highest-salary-in-sql/',
    neetCode: 'https://neetcode.io/problems/second-highest-salary',
    striverVideo: 'https://www.youtube.com/watch?v=0k5W1S_c_7c',
    companyTags: ['Infosys DSE', 'Infosys Technical Interview'],
    frequency: 98,
    status: 'Mastered',
    confidence: 5,
    expectedTime: 10,
    approach: 'SELECT MAX(salary) FROM Employee WHERE salary < (SELECT MAX(salary) FROM Employee); or use DENSE_RANK() OVER (ORDER BY salary DESC).'
  }
];

export const INITIAL_OA_EXPERIENCES: OAExperienceEntry[] = [
  {
    id: 'oa-exp-1',
    date: '2026-02-10',
    college: 'Vardhaman College of Engineering',
    role: 'SP',
    title: 'Smart City Sensor Network Power Routing',
    description: 'Given a grid of sensors with power costs and battery drain rates, find the minimum total power required to establish a continuous connected path from top-left to bottom-right, allowing at most K battery recharges.',
    extractedPattern: '18. Graph',
    extractedDifficulty: 'Hard',
    similarProblemName: 'Shortest Path in Binary Matrix / Dijkstra with K Recharges',
    verifiedInDrive: true
  },
  {
    id: 'oa-exp-2',
    date: '2026-01-28',
    college: 'Campus Drive (Zone South)',
    role: 'DSE',
    title: 'E-Commerce Package Batching',
    description: 'An array of package weights arriving in order. Pack them into trucks of maximum capacity C such that total trucks used is minimized and no package order is changed.',
    extractedPattern: '7. Binary Search',
    extractedDifficulty: 'Medium',
    similarProblemName: 'Capacity To Ship Packages Within D Days',
    verifiedInDrive: true
  },
  {
    id: 'oa-exp-3',
    date: '2025-11-15',
    college: 'HackWithInfy Grand Finale',
    role: 'SP',
    title: 'Maximum Subarray Xor Range Modification',
    description: 'Perform range updates on array and query maximum XOR subarray value after applying at most 2 operations.',
    extractedPattern: '22. Bit Manipulation',
    extractedDifficulty: 'Very Hard',
    similarProblemName: 'Maximum XOR Pair Trie + Prefix XOR',
    verifiedInDrive: true
  }
];
